# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = []

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    alt-j = 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-the-workspace'
    alt-k = 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-the-workspace'
    alt-l = 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-the-workspace'
    alt-down = 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-the-workspace'
    alt-up = 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-the-workspace'
    # alt-o = 'focus dfs-next --boundaries-action wrap-around-the-workspace'
    # alt-shift-o = 'focus dfs-next --boundaries-action wrap-around-the-workspace'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    ctrl-shift-h = 'move left --boundaries all-monitors-outer-frame'
    ctrl-shift-j = 'move down --boundaries all-monitors-outer-frame'
    ctrl-shift-k = 'move up --boundaries all-monitors-outer-frame'
    ctrl-shift-l = 'move right --boundaries all-monitors-outer-frame'
    ctrl-shift-down = 'move down --boundaries all-monitors-outer-frame'
    ctrl-shift-up = 'move up --boundaries all-monitors-outer-frame'
    ctrl-shift-y = ['join-with left', 'mode main']
    ctrl-shift-u = ['join-with down', 'mode main']
    ctrl-shift-i = ['join-with up', 'mode main']
    ctrl-shift-o = ['join-with right', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = ['workspace 1', 'move-mouse monitor-lazy-center']
    alt-2 = ['workspace 2', 'move-mouse monitor-lazy-center']
    alt-3 = ['workspace 3', 'move-mouse monitor-lazy-center']
    alt-4 = ['workspace 4', 'move-mouse monitor-lazy-center']
    alt-5 = ['workspace 5', 'move-mouse monitor-lazy-center']

    alt-q = ['workspace Q', 'move-mouse monitor-lazy-center']
    alt-w = ['workspace W', 'move-mouse monitor-lazy-center']
    alt-e = ['workspace E', 'move-mouse monitor-lazy-center']
    alt-r = ['workspace R', 'move-mouse monitor-lazy-center']

    alt-a = ['workspace A', 'move-mouse monitor-lazy-center']
    alt-s = ['workspace S', 'move-mouse monitor-lazy-center']
    alt-d = ['workspace D', 'move-mouse monitor-lazy-center']

    ctrl-shift-1 = 'move-node-to-workspace 1'
    ctrl-shift-2 = 'move-node-to-workspace 2'
    ctrl-shift-3 = 'move-node-to-workspace 3'
    ctrl-shift-4 = 'move-node-to-workspace 4'
    ctrl-shift-5 = 'move-node-to-workspace 5'

    ctrl-shift-q = 'move-node-to-workspace Q'
    ctrl-shift-w = 'move-node-to-workspace W'
    ctrl-shift-e = 'move-node-to-workspace E'
    ctrl-shift-r = 'move-node-to-workspace R'

    ctrl-shift-a = 'move-node-to-workspace A'
    ctrl-shift-s = 'move-node-to-workspace S'
    ctrl-shift-d = 'move-node-to-workspace D'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    alt-cmd-h = 'workspace prev'
    alt-cmd-l = 'workspace next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    ctrl-shift-semicolon = 'mode service'
    alt-shift-z = ['fullscreen', 'mode main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    p = ['exec-and-forget ~/.aerospace.rotate.sh', 'mode main']
    r = ['exec-and-forget ~/.aerospace.reload.sh', 'mode main']
    esc = 'mode main' # escape mode with no consequence
    backspace = ['flatten-workspace-tree', 'mode main'] # reset layout

    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

